# Publishes to PyPI upon creation of a release
name: Upload Package to PyPI

on:  # Runs everytime a release is added to the repository
  release:
    types: [created]

jobs:
  deploy:
    # uses: pylhc/.github/.github/workflows/publish.yml@master
    uses: pylhc/.github/.github/workflows/publish.yml@reusable_workflows
    secrets: inherit
